spring:
  profiles.active: dev
  freemarker.cache: false
  #  kafka配置
  kafka:
    consumer:
      bootstrap-servers: 10.0.11.50:19092
      group-id: tsp-transfer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      bootstrap-servers: 10.0.11.50:19092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
  data:
    #redis配置
    #如果都进行了配置,加载的先后顺序为:
    #sentinel>cluster>single
    redis:
      ssl:
        enabled: false
      repositories:
        enabled: false
      #公用配置
      database: 0
      timeout: 60000
      password: wq
      #异步lettuce连接池(默认)
      lettuce:
        pool:
          maxIdle: 8
          minIdle: 0
          maxActive: 8
          maxWait: -1
        shutdown-timeout: 100ms
      #单机配置
      host: 10.0.11.50
      port: 36379


transfer:
  serverId: gb1
lib:
  spring:
    data:
      notify:
        vehicleData:
          groupId: "notify-vehicle"
        platformStatus:
          enableSender: true











